version: '2.3'

services:
  tf_gpu:
    build: .
    image: hironsan-mynavi/tensorflow-gpu:9.7
    container_name: tensorflow_gpu
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/work
    command: /bin/bash
    tty: true
